[package]
name = "ewire-libraly-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "競技プログラミング用ライブラリ"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
