[package]
name = "cp_library_rs"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
description = "競技プログラミング用ライブラリ"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_prime = {path = "./crates/math/number_theory/is_prime" }